# Generated by Django 2.2.6 on 2019-11-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProffession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_name', models.CharField(max_length=120)),
                ('doner_phone', models.CharField(max_length=15)),
                ('doner_email', models.EmailField(blank=True, max_length=50)),
                ('doner_pass', models.CharField(max_length=300)),
                ('doner_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatherProffession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoorPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(default='ç', max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('father_name', models.CharField(max_length=150)),
                ('father_contact_number', models.IntegerField()),
                ('mother_name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('amount_received', models.IntegerField(default=0)),
                ('require_date', models.DateField()),
                ('address', models.TextField(max_length=500)),
                ('bank_account', models.IntegerField(blank=True, null=True)),
                ('bkash_account', models.IntegerField(blank=True, null=True)),
                ('identity_doc', models.ImageField(upload_to='uploads/')),
                ('nid_number', models.IntegerField(blank=True, null=True)),
                ('passport_number', models.IntegerField(blank=True, null=True)),
                ('driving_license', models.IntegerField(blank=True, null=True)),
                ('birth_certificate_number', models.IntegerField(blank=True, null=True)),
                ('document_file_one', models.ImageField(blank=True, upload_to='uploads/')),
                ('document_file_two', models.ImageField(blank=True, upload_to='uploads/')),
                ('document_file_three', models.ImageField(blank=True, upload_to='uploads/')),
                ('problem_description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('complete_status', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('aplicant_proffessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.ApplicantProffession')),
                ('father_proffession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.FatherProffession')),
                ('help_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.HelpCategory')),
                ('identity_doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.VerifiedDocument')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='PermessionCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_action', models.BooleanField(default=False)),
                ('delete_action', models.BooleanField(default=False)),
                ('update_action', models.BooleanField(default=False)),
                ('insert_action', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.PoorPeople')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('transaction_num', models.CharField(blank=True, default='123', max_length=100)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('payment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.Doner')),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.PoorPeople')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.PaymentType')),
            ],
        ),
    ]
