# Generated by Django 2.2.6 on 2019-11-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0002_blodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='blood_groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.BlodGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='blood_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.BlodGroup'),
            preserve_default=False,
        ),
    ]
