# Generated by Django 2.2.6 on 2019-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0003_auto_20191110_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
    ]
