# Generated by Django 2.2.6 on 2019-11-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0005_citylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.CityList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.CityList'),
            preserve_default=False,
        ),
    ]
