# Generated by Django 2.2.6 on 2019-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0006_auto_20191110_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocess',
            name='transaction_num',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
