# Generated by Django 2.2.6 on 2019-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0009_paymenttype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
