# Generated by Django 2.2.6 on 2019-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0010_auto_20191112_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocess',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentprocess',
            name='bkash_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
