# Generated by Django 2.2.6 on 2019-11-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0011_auto_20191112_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocess',
            name='transaction_num',
            field=models.SlugField(max_length=12, null=True, unique=True),
        ),
    ]
