# Generated by Django 2.2.6 on 2019-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0015_auto_20191112_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocess',
            name='transaction_num',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
