# Generated by Django 2.2.6 on 2019-11-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0016_auto_20191113_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='district_ist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.DistrictList'),
        ),
    ]
