# Generated by Django 2.2.6 on 2019-11-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0017_doner_district_ist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doner',
            old_name='district_ist',
            new_name='district_name',
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='district_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poorapp.DistrictList'),
        ),
    ]
