# Generated by Django 2.2.6 on 2019-11-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0019_auto_20191118_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonerLoginHisoty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_ip', models.CharField(max_length=20)),
                ('login_date', models.DateField(auto_now_add=True)),
                ('login_status', models.BooleanField(default=True)),
                ('doner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorapp.Doner')),
            ],
        ),
    ]
