# Generated by Django 2.2.6 on 2019-11-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0020_donerloginhisoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='bkash_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
