# Generated by Django 2.2.6 on 2019-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0021_auto_20191123_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='birth_certificate_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='driving_license',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='nid_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
