# Generated by Django 2.2.6 on 2019-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0022_auto_20191123_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpeople',
            name='post_code',
            field=models.CharField(default=2020, max_length=20),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
