# Generated by Django 2.2.6 on 2019-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0023_auto_20191125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='post_code',
            field=models.CharField(max_length=20),
        ),
    ]
