# Generated by Django 2.2.6 on 2019-11-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0024_auto_20191125_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poorpeople',
            old_name='driving_license',
            new_name='identity_number',
        ),
        migrations.RemoveField(
            model_name='poorpeople',
            name='nid_number',
        ),
        migrations.RemoveField(
            model_name='poorpeople',
            name='passport_number',
        ),
    ]
