# Generated by Django 2.2.6 on 2019-11-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0026_auto_20191125_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poorpeople',
            old_name='bank_account',
            new_name='payment_account',
        ),
        migrations.RemoveField(
            model_name='poorpeople',
            name='bkash_account',
        ),
    ]
