# Generated by Django 2.2.6 on 2019-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0028_auto_20191125_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poorpeople',
            name='birth_certificate_number',
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='blood_group',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'AB+'), ('4', 'AB-'), ('5', 'B+'), ('6', 'B-'), ('7', 'O+'), ('8', 'O-')], default=1, max_length=1),
        ),
    ]
