# Generated by Django 2.2.6 on 2019-11-28 15:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0029_auto_20191127_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='identity_doc_type',
            field=models.CharField(choices=[('DL', 'Driving License'), ('PP', 'Passport'), ('NC', 'NID Card'), ('BC', 'Birth Certificate')], max_length=2),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='problem_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
