# Generated by Django 2.2.6 on 2020-01-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0030_auto_20191128_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddoner',
            name='bdoner_gender',
        ),
    ]
