# Generated by Django 2.2.6 on 2020-01-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0032_blooddoner_bdoner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddoner',
            name='bdoner_pass',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
