# Generated by Django 4.2.13 on 2024-06-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0034_remove_doner_blood_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlodGroup',
        ),
    ]
