# Generated by Django 4.2.13 on 2024-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0035_delete_blodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpeople',
            name='cloth_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='cloth_size',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='edu_items',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='poorpeople',
            name='food_quantity',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
