# Generated by Django 4.2.13 on 2024-06-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0036_poorpeople_cloth_count_poorpeople_cloth_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poorpeople',
            name='document_file_three',
        ),
        migrations.RemoveField(
            model_name='poorpeople',
            name='document_file_two',
        ),
    ]
