# Generated by Django 4.2.13 on 2024-06-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0037_remove_poorpeople_document_file_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='food_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poorpeople',
            name='payment_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poorapp.paymenttype'),
        ),
    ]
