# Generated by Django 4.2.13 on 2024-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0038_alter_poorpeople_food_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpeople',
            name='food_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
