# Generated by Django 4.2.13 on 2024-06-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0039_poorpeople_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorpeople',
            name='payment_type',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='poorapp.paymenttype'),
        ),
    ]
