# Generated by Django 4.2.13 on 2024-06-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorapp', '0041_doner_complete_doner_request_alter_doner_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoorPeople',
            new_name='Receivers',
        ),
    ]
